FROM redis:7-alpine

# Enable Redis persistence
RUN echo "appendonly yes" >> /usr/local/etc/redis/redis.conf
RUN echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf

EXPOSE 6379

CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
