# Filepath: render.yaml

services:
  - type: web
    name: tubealgo
    env: python
    plan: free

    # Build command tells Render to execute your script
    buildCommand: "./build.sh"

    # Start command runs your application with Gunicorn
    startCommand: "gunicorn run:app"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tubealgo-database # Make sure this matches your database name on Render
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 20.10.0
      - key: SECRET_KEY
        generateValue: true
      
      - key: YOUTUBE_API_KEYS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MEASUREMENT_ID
        sync: false

      # --- REMOVE RAZORPAY KEYS ---
      # - key: RAZORPAY_KEY_ID
      #   sync: false
      # - key: RAZORPAY_KEY_SECRET
      #   sync: false
        
      # +++ ADD CASHFREE KEYS HERE +++
      - key: CASHFREE_APP_ID
        sync: false
      - key: CASHFREE_SECRET_KEY
        sync: false
      - key: CASHFREE_ENV
        value: "PROD" # या "PROD" जब आप लाइव होंगे

    autoDeploy: true
