# Filepath: render.yaml

services:
  - type: web
    name: tubealgo
    env: python
    plan: free

    buildCommand: "./build.sh"
    startCommand: "gunicorn run:app"

    envVars:
      # === महत्वपूर्ण बदलाव यहाँ है ===
      # हमने fromDatabase सेक्शन को हटा दिया है क्योंकि अब हम इसे सीधे डैशबोर्ड से सेट कर रहे हैं।
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 20.10.0
      - key: SECRET_KEY
        generateValue: true
      
      # ये सभी Keys आपके Render डैशबोर्ड के "Environment" सेक्शन में होनी चाहिए
      - key: DATABASE_URL
        sync: false
      - key: YOUTUBE_API_KEYS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MEASUREMENT_ID
        sync: false
      - key: CASHFREE_APP_ID
        sync: false
      - key: CASHFREE_SECRET_KEY
        sync: false
      - key: CASHFREE_ENV
        value: "PROD"

    autoDeploy: true

# यह सुनिश्चित करने के लिए कि आपका डेटाबेस मौजूद है, इस सेक्शन को YAML में रखें।
databases:
  - name: tubealgo-database # यह नाम आपके डेटाबेस के नाम से मेल खाना चाहिए
    databaseName: tubealgodb 
    user: tubealgouser
