# render.yaml

services:
  # 1. Redis Service
  - name: tubealgo-redis
    type: pserv
    env: docker
    dockerfilePath: ./Dockerfile.redis
    dockerContext: .
    plan: free
    disk:
      name: redis-data
      mountPath: /data
      sizeGB: 1

  # 2. Web Service (Flask application)
  - type: web
    name: tubealgo-web
    env: python
    plan: free
    buildCommand: |
      echo "=== Starting TubeAlgo Build ==="
      pip install --upgrade pip
      npm install
      npm run build
      pip install -r requirements.txt
      echo "=== Creating Database Tables ==="
      python create_tables.py
      echo "=== Build Complete ==="
    startCommand: "gunicorn -c gunicorn.conf.py run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 20.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        fromService: 
          type: pserv
          name: tubealgo-redis
          property: connectionString
      - key: FLASK_APP
        value: "run.py"
      - key: FLASK_ENV
        value: "production"
      - key: DATABASE_URL
        fromDatabase:
          name: tubealgo-database
          property: connectionString
      # Celery Settings
      - key: CELERY_TASK_IGNORE_RESULT
        value: "True"
      - key: CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP
        value: "True"
      # --- Other secrets ---
      - key: YOUTUBE_API_KEYS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_CHAT_ID
        sync: false
      - key: MEASUREMENT_ID
        sync: false
      - key: CASHFREE_APP_ID
        sync: false
      - key: CASHFREE_SECRET_KEY
        sync: false
      - key: CASHFREE_ENV
        value: "PROD"

  # 3. Celery Worker Service
  - type: worker
    name: tubealgo-celery-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A tubealgo.celery worker --loglevel=info --pool=solo"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: REDIS_URL
        fromService:
          type: pserv
          name: tubealgo-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: tubealgo-database
          property: connectionString
      - key: FLASK_ENV
        value: "production"
      - key: CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP
        value: "True"
      # --- secrets ---
      - key: YOUTUBE_API_KEYS
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_CHAT_ID
        sync: false

  # 4. Celery Beat Service
  - type: worker
    name: tubealgo-celery-beat
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A tubealgo.celery beat --loglevel=info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: REDIS_URL
        fromService:
          type: pserv
          name: tubealgo-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: tubealgo-database
          property: connectionString
      - key: FLASK_ENV
        value: "production"
      - key: CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP
        value: "True"
      # --- secrets ---
      - key: YOUTUBE_API_KEYS
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_CHAT_ID
        sync: false

databases:
  - name: tubealgo-database
    databaseName: tubealgodb
    user: tubealgouser
    plan: free
